name: Upload OpenAPI Spec to Stainless
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    name: Stainless — Upload OpenAPI specification
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'openapi.yaml'
          output_path: 'openapi.documented.yaml'
          project_name: 'togetherai'
          guess_config: true
      # - uses: readmeio/rdme@v8
      #   with:
      #     rdme: openapi "openapi.documented.yaml" --key=${{ secrets.README_TOKEN }} --id=${{ secrets.README_DEFINITION_ID }}
